# verification token for Facebook callback URL verification
VERIFICATION_TOKEN_DEFAULT = 'pGZlgwRCBO'
IBM_WATSON_APIKEY_DEFAULT = 'm-J7XSa8Be-8JS2LzAsneKU6G8_Fn7TM3aHbc0Nnc5WD'
DATABASE_URL_DEFAULT = "mongodb+srv://emotion_bot:Parwad123!@cluster0-iy6yd.mongodb.net/test?retryWrites=true"
PAGE_ACCESS_TOKEN_DEFAULT = 'EAAEZAkfVPsO8BAFZBaXSfr4EhXMo2Qv75Oq4RjZBaNrZBYCSUIaT80uGinPArzK0DEhotKKBpsLucEQiY0mmWekbvCjQWOvDBSe26IWnFT7FiEc0TVjAXwJgURiZAO2luSjYI3hNhZCdCC0gZAEmLlPkjPZBzMObZBRp5zoojk1IwwQZDZD'
